apiVersion: v1
kind: ConfigMap
metadata:
  name: shopapi-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "3000"
  APP_NAME: "ShopAPI"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgres://shopuser:shoppass@postgres-service:5432/shopdb"